### ISSUE TITLE
Add button to toolbar

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/Quora-Nightly#1]
Add button for enabling/disabling this extension on your browser.
Simple how-to tutorial:
[WebExtension - add a button to the toolbar](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Add_a_button_to_the_toolbar)

**Comment by hamzabasrai** [comment]
I can add this feature

**Comment by mecm1993** [comment]
This issue was resolved [here](https://github.com/TheAdnan/Quora-Nightly/pull/4). So, it should be closed.
